### ISSUE TITLE
Add hyperlink in issue tracker (readme file)

### ISSUE THREAD

**Issue by tawhidmonowar** [tawhidmonowar/URLtoPDFConverter#12]
In contributing section when user click on "issue tracker" it should open this link: https://github.com/tawhidmonowar/URLtoPDFConverter/issues

**Comment by CYBWEBALI** [comment]
Can you assign this issue to me?

**Comment by tawhidmonowar** [comment]
> Can you assign this issue to me?

Issue assigned as requested. Thank you for your willingness to contribute.

**Comment by CYBWEBALI** [comment]
Done. PR #13

**Comment by tawhidmonowar** [comment]
Thank you for the PR, don't forget to give a star. Your star would help increase the visibility of the project.
