### ISSUE TITLE
Unable to open URL

### ISSUE THREAD

**Issue by benjamir** [tawhidmonowar/URLtoPDFConverter#19]
There's a slash added to the inserted URL. Editing the URL isn't working.
Searching via the provided search engines is more then cumbersome -- the site was found via another one easily.

**Comment by tawhidmonowar** [comment]
Thank you for reaching out and bringing this issue to my attention. I look forward to resolving this issue.

**Comment by tawhidmonowar** [comment]
Issue (#19) solved. 
@benjamir @HarriBuh If you enjoyed the project, a star would be a wonderful way to show your support.

**Comment by benjamir** [comment]
Sorry, @tawhidmonowar I was not able to use your app on my phone, yet. F-droid has the same version as stable release (I don't see and use beta releases).
But thanks for the pointer to the closed issue. If there will be a release which works for me, I'll be happy to star your repo. All the best, Benjamin

**Comment by tawhidmonowar** [comment]
I'm updating the UI and adding some new features, I will release a new version soon.

**Comment by tawhidmonowar** [comment]
> Sorry, @tawhidmonowar I was not able to use your app on my phone, yet. F-droid has the same version as stable release (I don't see and use beta releases). But thanks for the pointer to the closed issue. If there will be a release which works for me, I'll be happy to star your repo. All the best, Benjamin

I'm updating the UI and adding some new features, I will release a new version soon.
